### Project Name:- Customer Churn Prediction

### Problem :-
Retaining existing customers is significantly more cost-effective than acquiring new ones, yet many businesses lack the ability to identify "at-risk" customers before they leave. Undetected churn gradually damages brand trust, reduces lifetime customer value, and weakens long-term growth.

### Solution:-
This project Aim to solve that problem by building a prediction system that help to detect customers who likely to churn -  early enough for the business to act."

## Data Cleaning:

In [65]:
# step 0: import libraries
import os
import numpy as np
import pandas as pd

In [66]:
# step 1: load the data

dataset_1 = pd.read_csv('../data/raw/customer_churn_prediction_dataset.csv')

In [67]:
print(dataset_1.shape)
dataset_1.head(10)

(300, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0001-XXXX,Male,0,Yes,Yes,5,No,Yes,No,No,...,No,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,Yes
1,0002-XXXX,Female,0,No,No,42,Yes,No phone service,DSL,Yes,...,No,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,Yes
2,0003-XXXX,Male,0,No,No,61,Yes,No phone service,No,No,...,No,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,Yes
3,0004-XXXX,Male,1,No,Yes,22,Yes,No,No,No internet service,...,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,No
4,0005-XXXX,Male,1,Yes,Yes,21,No,No,DSL,No,...,No internet service,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,Yes
5,0006-XXXX,Female,0,Yes,No,70,Yes,No phone service,No,No internet service,...,Yes,No internet service,No internet service,Yes,Month-to-month,Yes,Electronic check,43.21,3024.70,No
6,0007-XXXX,Male,1,Yes,No,1,No,No,DSL,No,...,No internet service,Yes,No internet service,Yes,Month-to-month,No,Credit card,39.80,39.80,Yes
7,0008-XXXX,Male,1,No,Yes,5,No,Yes,No,No,...,No internet service,Yes,No,No internet service,Month-to-month,No,Credit card,45.47,227.35,No
8,0009-XXXX,Male,1,No,Yes,12,No,Yes,DSL,No,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer,43.13,517.56,No
9,0010-XXXX,Female,1,No,No,46,Yes,No,Fiber optic,No,...,No internet service,No,No internet service,Yes,Month-to-month,Yes,Electronic check,24.53,1128.38,Yes

In [68]:
# load second dataset
dataset_2 = pd.read_csv('../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [69]:
print(dataset_2.shape)
dataset_2.head(10)

(7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

### 02. Data preprocessing

In [70]:
print(dataset_1.info())

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        300 non-null    str
 1   gender            300 non-null    str
 2   SeniorCitizen     300 non-null    int64
 3   Partner           300 non-null    str
 4   Dependents        300 non-null    str
 5   tenure            300 non-null    int64
 6   PhoneService      300 non-null    str
 7   MultipleLines     300 non-null    str
 8   InternetService   300 non-null    str
 9   OnlineSecurity    300 non-null    str
 10  OnlineBackup      300 non-null    str
 11  DeviceProtection  300 non-null    str
 12  TechSupport       300 non-null    str
 13  StreamingTV       300 non-null    str
 14  StreamingMovies   300 non-null    str
 15  Contract          300 non-null    str
 16  PaperlessBilling  300 non-null    str
 17  PaymentMethod     300 non-null    str
 18  MonthlyCharges    300 non-null    float64
 19  TotalCharges      300 non-null    float64
 20  Churn             300 non-null    str
dtypes: float64(2), int64(2), str(17)
memory usage: 49.3 KB
None

In [71]:
print(dataset_2.info())

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB
None

In [72]:
# changing the total charges column to float64
dataset_2['TotalCharges'] = pd.to_numeric(dataset_2['TotalCharges'], errors='coerce')
print(dataset_2.info())

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB
None

In [73]:
# step 2: merging the datasets
merged_dataset = pd.concat([dataset_1, dataset_2], axis=0)
print(merged_dataset.shape)
merged_dataset.head(10)

(7343, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0001-XXXX,Male,0,Yes,Yes,5,No,Yes,No,No,...,No,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,Yes
1,0002-XXXX,Female,0,No,No,42,Yes,No phone service,DSL,Yes,...,No,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,Yes
2,0003-XXXX,Male,0,No,No,61,Yes,No phone service,No,No,...,No,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,Yes
3,0004-XXXX,Male,1,No,Yes,22,Yes,No,No,No internet service,...,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,No
4,0005-XXXX,Male,1,Yes,Yes,21,No,No,DSL,No,...,No internet service,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,Yes
5,0006-XXXX,Female,0,Yes,No,70,Yes,No phone service,No,No internet service,...,Yes,No internet service,No internet service,Yes,Month-to-month,Yes,Electronic check,43.21,3024.70,No
6,0007-XXXX,Male,1,Yes,No,1,No,No,DSL,No,...,No internet service,Yes,No internet service,Yes,Month-to-month,No,Credit card,39.80,39.80,Yes
7,0008-XXXX,Male,1,No,Yes,5,No,Yes,No,No,...,No internet service,Yes,No,No internet service,Month-to-month,No,Credit card,45.47,227.35,No
8,0009-XXXX,Male,1,No,Yes,12,No,Yes,DSL,No,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer,43.13,517.56,No
9,0010-XXXX,Female,1,No,No,46,Yes,No,Fiber optic,No,...,No internet service,No,No internet service,Yes,Month-to-month,Yes,Electronic check,24.53,1128.38,Yes

In [74]:
print(merged_dataset.info() )

<class 'pandas.DataFrame'>
Index: 7343 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7343 non-null   str
 1   gender            7343 non-null   str
 2   SeniorCitizen     7343 non-null   int64
 3   Partner           7343 non-null   str
 4   Dependents        7343 non-null   str
 5   tenure            7343 non-null   int64
 6   PhoneService      7343 non-null   str
 7   MultipleLines     7343 non-null   str
 8   InternetService   7343 non-null   str
 9   OnlineSecurity    7343 non-null   str
 10  OnlineBackup      7343 non-null   str
 11  DeviceProtection  7343 non-null   str
 12  TechSupport       7343 non-null   str
 13  StreamingTV       7343 non-null   str
 14  StreamingMovies   7343 non-null   str
 15  Contract          7343 non-null   str
 16  PaperlessBilling  7343 non-null   str
 17  PaymentMethod     7343 non-null   str
 18  MonthlyCharges    7343 non-null   float64
 19  TotalCharges      7332 non-null   float64
 20  Churn             7343 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.2 MB
None

In [75]:
# checking for missing values
print(merged_dataset.isnull().sum())

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [76]:
# checking for Null valus
print(merged_dataset.isnull().sum())

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [77]:
# 1. mapping churn column to binary values
merged_dataset['Churn'] = merged_dataset['Churn'].map({'Yes': 1, 'No': 0})

# 2. mapping gender column to binary values
merged_dataset['gender'] = merged_dataset['gender'].apply(lambda x: 1 if x == 'Male' else 0)


merged_dataset.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0001-XXXX,1,0,Yes,Yes,5,No,Yes,No,No,...,No,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,1
1,0002-XXXX,0,0,No,No,42,Yes,No phone service,DSL,Yes,...,No,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,1
2,0003-XXXX,1,0,No,No,61,Yes,No phone service,No,No,...,No,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,1
3,0004-XXXX,1,1,No,Yes,22,Yes,No,No,No internet service,...,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,0
4,0005-XXXX,1,1,Yes,Yes,21,No,No,DSL,No,...,No internet service,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,1
5,0006-XXXX,0,0,Yes,No,70,Yes,No phone service,No,No internet service,...,Yes,No internet service,No internet service,Yes,Month-to-month,Yes,Electronic check,43.21,3024.70,0
6,0007-XXXX,1,1,Yes,No,1,No,No,DSL,No,...,No internet service,Yes,No internet service,Yes,Month-to-month,No,Credit card,39.80,39.80,1
7,0008-XXXX,1,1,No,Yes,5,No,Yes,No,No,...,No internet service,Yes,No,No internet service,Month-to-month,No,Credit card,45.47,227.35,0
8,0009-XXXX,1,1,No,Yes,12,No,Yes,DSL,No,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer,43.13,517.56,0
9,0010-XXXX,0,1,No,No,46,Yes,No,Fiber optic,No,...,No internet service,No,No internet service,Yes,Month-to-month,Yes,Electronic check,24.53,1128.38,1

In [78]:
# replacing No internet service or No phone service with No
cols = ['MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

for col in cols:
    merged_dataset[col] = merged_dataset[col].replace({'No internet service': 'No', 'No phone service': 'No'})

merged_dataset.head(10)


#reason:
#1. No internet service and No phone service are essentially the same as No for the respective services.
#2. This replacement simplifies the dataset and reduces the number of unique values in these columns, 
# which can help improve the performance of machine learning models by reducing complexity and potential noise in the data.
# 3. It also makes it easier to interpret the data, as it clearly indicates that the customer does not have the service, 
# rather than having a separate category for those who do not have internet or phone service.

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0001-XXXX,1,0,Yes,Yes,5,No,Yes,No,No,...,No,No,No,No,Month-to-month,Yes,Credit card,27.43,137.15,1
1,0002-XXXX,0,0,No,No,42,Yes,No,DSL,Yes,...,No,No,No,No,Two year,No,Electronic check,38.28,1607.76,1
2,0003-XXXX,1,0,No,No,61,Yes,No,No,No,...,No,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,1
3,0004-XXXX,1,1,No,Yes,22,Yes,No,No,No,...,Yes,No,No,Yes,Month-to-month,No,Electronic check,92.49,2034.78,0
4,0005-XXXX,1,1,Yes,Yes,21,No,No,DSL,No,...,No,No,No,No,One year,No,Bank transfer,19.63,412.23,1
5,0006-XXXX,0,0,Yes,No,70,Yes,No,No,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,43.21,3024.70,0
6,0007-XXXX,1,1,Yes,No,1,No,No,DSL,No,...,No,Yes,No,Yes,Month-to-month,No,Credit card,39.80,39.80,1
7,0008-XXXX,1,1,No,Yes,5,No,Yes,No,No,...,No,Yes,No,No,Month-to-month,No,Credit card,45.47,227.35,0
8,0009-XXXX,1,1,No,Yes,12,No,Yes,DSL,No,...,No,No,No,No,Two year,Yes,Bank transfer,43.13,517.56,0
9,0010-XXXX,0,1,No,No,46,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,24.53,1128.38,1

In [79]:
# maping the categorical columns to numerical values
cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

for col in cols:
    merged_dataset[col] = merged_dataset[col].map({'Yes': 1, 'No': 0})

merged_dataset.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0001-XXXX,1,0,1,1,5,0,1,No,0,...,0,0,0,0,Month-to-month,1,Credit card,27.43,137.15,1
1,0002-XXXX,0,0,0,0,42,1,0,DSL,1,...,0,0,0,0,Two year,0,Electronic check,38.28,1607.76,1
2,0003-XXXX,1,0,0,0,61,1,0,No,0,...,0,1,1,0,One year,0,Bank transfer,106.44,6492.84,1
3,0004-XXXX,1,1,0,1,22,1,0,No,0,...,1,0,0,1,Month-to-month,0,Electronic check,92.49,2034.78,0
4,0005-XXXX,1,1,1,1,21,0,0,DSL,0,...,0,0,0,0,One year,0,Bank transfer,19.63,412.23,1
5,0006-XXXX,0,0,1,0,70,1,0,No,0,...,1,0,0,1,Month-to-month,1,Electronic check,43.21,3024.70,0
6,0007-XXXX,1,1,1,0,1,0,0,DSL,0,...,0,1,0,1,Month-to-month,0,Credit card,39.80,39.80,1
7,0008-XXXX,1,1,0,1,5,0,1,No,0,...,0,1,0,0,Month-to-month,0,Credit card,45.47,227.35,0
8,0009-XXXX,1,1,0,1,12,0,1,DSL,0,...,0,0,0,0,Two year,1,Bank transfer,43.13,517.56,0
9,0010-XXXX,0,1,0,0,46,1,0,Fiber optic,0,...,0,0,0,1,Month-to-month,1,Electronic check,24.53,1128.38,1

In [80]:
# droping the ustomerId and TotalCharges columns
merged_dataset.drop(['customerID', 'TotalCharges'], axis=1, inplace=True)
print(merged_dataset.info())

<class 'pandas.DataFrame'>
Index: 7343 entries, 0 to 7042
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7343 non-null   int64
 1   SeniorCitizen     7343 non-null   int64
 2   Partner           7343 non-null   int64
 3   Dependents        7343 non-null   int64
 4   tenure            7343 non-null   int64
 5   PhoneService      7343 non-null   int64
 6   MultipleLines     7343 non-null   int64
 7   InternetService   7343 non-null   str
 8   OnlineSecurity    7343 non-null   int64
 9   OnlineBackup      7343 non-null   int64
 10  DeviceProtection  7343 non-null   int64
 11  TechSupport       7343 non-null   int64
 12  StreamingTV       7343 non-null   int64
 13  StreamingMovies   7343 non-null   int64
 14  Contract          7343 non-null   str
 15  PaperlessBilling  7343 non-null   int64
 16  PaymentMethod     7343 non-null   str
 17  MonthlyCharges    7343 non-null   float64
 18  Churn             7343 non-null   int64
dtypes: float64(1), int64(15), str(3)
memory usage: 1.1 MB
None

In [81]:
# # one hot encoding the categorical columns
# merged_dataset = pd.get_dummies(merged_dataset, columns=['InternetService','PaymentMethod'], drop_first=True)
# merged_dataset.head(10)

In [82]:
print(merged_dataset.info())

<class 'pandas.DataFrame'>
Index: 7343 entries, 0 to 7042
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7343 non-null   int64
 1   SeniorCitizen     7343 non-null   int64
 2   Partner           7343 non-null   int64
 3   Dependents        7343 non-null   int64
 4   tenure            7343 non-null   int64
 5   PhoneService      7343 non-null   int64
 6   MultipleLines     7343 non-null   int64
 7   InternetService   7343 non-null   str
 8   OnlineSecurity    7343 non-null   int64
 9   OnlineBackup      7343 non-null   int64
 10  DeviceProtection  7343 non-null   int64
 11  TechSupport       7343 non-null   int64
 12  StreamingTV       7343 non-null   int64
 13  StreamingMovies   7343 non-null   int64
 14  Contract          7343 non-null   str
 15  PaperlessBilling  7343 non-null   int64
 16  PaymentMethod     7343 non-null   str
 17  MonthlyCharges    7343 non-null   float64
 18  Churn             7343 non-null   int64
dtypes: float64(1), int64(15), str(3)
memory usage: 1.1 MB
None

In [83]:
merged_dataset = merged_dataset.drop_duplicates()
print(merged_dataset.shape)  # confirm 27 rows removed

(7316, 19)

In [84]:
merged_dataset.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,Churn
0,1,0,1,1,5,0,1,No,0,1,0,0,0,0,Month-to-month,1,Credit card,27.43,1
1,0,0,0,0,42,1,0,DSL,1,1,0,0,0,0,Two year,0,Electronic check,38.28,1
2,1,0,0,0,61,1,0,No,0,1,0,1,1,0,One year,0,Bank transfer,106.44,1
3,1,1,0,1,22,1,0,No,0,0,1,0,0,1,Month-to-month,0,Electronic check,92.49,0
4,1,1,1,1,21,0,0,DSL,0,0,0,0,0,0,One year,0,Bank transfer,19.63,1
5,0,0,1,0,70,1,0,No,0,1,1,0,0,1,Month-to-month,1,Electronic check,43.21,0
6,1,1,1,0,1,0,0,DSL,0,0,0,1,0,1,Month-to-month,0,Credit card,39.80,1
7,1,1,0,1,5,0,1,No,0,0,0,1,0,0,Month-to-month,0,Credit card,45.47,0
8,1,1,0,1,12,0,1,DSL,0,0,0,0,0,0,Two year,1,Bank transfer,43.13,0
9,0,1,0,0,46,1,0,Fiber optic,0,0,0,0,0,1,Month-to-month,1,Electronic check,24.53,1

In [85]:
print(merged_dataset.duplicated().sum())

0

In [87]:
# merged_dataset.head(10)

In [88]:
# # converting  contract column to ordinal values
# merged_dataset['Contract'] = merged_dataset['Contract'].map({
#     "Month-to-month": 0,
#     "One year": 1,
#     "Two year": 2
# })

In [89]:
# # check unquie value in tenure column
# print(merged_dataset['tenure'].unique())

In [90]:
# # converting the tenure column to bins
# bins = [0,12,48,72]
# labels = ['Early', 'Mid', 'Long']
# merged_dataset['tenure_group'] = pd.cut(merged_dataset['tenure'], bins=bins, labels=labels)

In [91]:
# merged_dataset.head(10)

In [92]:
# merged_dataset['tenure_group'] = merged_dataset['tenure_group'].map({
#     "Early": 0,
#     "Mid": 1,
#     "Long": 2
# })

In [95]:
# creating directory if it doesn't exist
if not os.path.exists('DATA/processed'):
    os.makedirs('DATA/processed')

# save full clean dataset 
merged_dataset.to_csv('../data/processed_data/clean_data.csv', index=False)