## 03 Feature Engineering

In [130]:
import numpy as np
import pandas as pd
import os

In [131]:
# Load the dataset
df = pd.read_csv('../data/processed_data/clean_data.csv')

# check info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7316 entries, 0 to 7315
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7316 non-null   int64
 1   SeniorCitizen     7316 non-null   int64
 2   Partner           7316 non-null   int64
 3   Dependents        7316 non-null   int64
 4   tenure            7316 non-null   int64
 5   PhoneService      7316 non-null   int64
 6   MultipleLines     7316 non-null   int64
 7   InternetService   7316 non-null   str
 8   OnlineSecurity    7316 non-null   int64
 9   OnlineBackup      7316 non-null   int64
 10  DeviceProtection  7316 non-null   int64
 11  TechSupport       7316 non-null   int64
 12  StreamingTV       7316 non-null   int64
 13  StreamingMovies   7316 non-null   int64
 14  Contract          7316 non-null   str
 15  PaperlessBilling  7316 non-null   int64
 16  PaymentMethod     7316 non-null   str
 17  MonthlyCharges    7316 non-null   float64
 18  Churn             7316 non-null   int64
dtypes: float64(1), int64(15), str(3)
memory usage: 1.1 MB

In [132]:
df.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,Churn
0,1,0,1,1,5,0,1,No,0,1,0,0,0,0,Month-to-month,1,Credit card,27.43,1
1,0,0,0,0,42,1,0,DSL,1,1,0,0,0,0,Two year,0,Electronic check,38.28,1
2,1,0,0,0,61,1,0,No,0,1,0,1,1,0,One year,0,Bank transfer,106.44,1
3,1,1,0,1,22,1,0,No,0,0,1,0,0,1,Month-to-month,0,Electronic check,92.49,0
4,1,1,1,1,21,0,0,DSL,0,0,0,0,0,0,One year,0,Bank transfer,19.63,1
5,0,0,1,0,70,1,0,No,0,1,1,0,0,1,Month-to-month,1,Electronic check,43.21,0
6,1,1,1,0,1,0,0,DSL,0,0,0,1,0,1,Month-to-month,0,Credit card,39.80,1
7,1,1,0,1,5,0,1,No,0,0,0,1,0,0,Month-to-month,0,Credit card,45.47,0
8,1,1,0,1,12,0,1,DSL,0,0,0,0,0,0,Two year,1,Bank transfer,43.13,0
9,0,1,0,0,46,1,0,Fiber optic,0,0,0,0,0,1,Month-to-month,1,Electronic check,24.53,1

In [133]:
# encoding categorical variables

df_encoded = df.copy()

In [134]:
#one-hot encoding
df_encoded = pd.get_dummies(df_encoded, columns=['InternetService', 'PaymentMethod'], drop_first=True)

# ordinal encoding
df_encoded['Contract'] = df_encoded['Contract'].map({'Month-to-month': 0, 'One year': 1, 'Two year': 2})

In [135]:
cols = ["InternetService_Fiber optic", "InternetService_No",
        "PaymentMethod_Bank transfer (automatic)", 
        "PaymentMethod_Credit card",
        "PaymentMethod_Credit card (automatic)",
        "PaymentMethod_Electronic check", 
        "PaymentMethod_Mailed check"]

df_encoded[cols] = df_encoded[cols].astype(int)

In [136]:
df_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 7316 entries, 0 to 7315
Data columns (total 24 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   gender                                   7316 non-null   int64
 1   SeniorCitizen                            7316 non-null   int64
 2   Partner                                  7316 non-null   int64
 3   Dependents                               7316 non-null   int64
 4   tenure                                   7316 non-null   int64
 5   PhoneService                             7316 non-null   int64
 6   MultipleLines                            7316 non-null   int64
 7   OnlineSecurity                           7316 non-null   int64
 8   OnlineBackup                             7316 non-null   int64
 9   DeviceProtection                         7316 non-null   int64
 10  TechSupport                              7316 non-null   int64
 11  StreamingTV                              7316 non-null   int64
 12  StreamingMovies                          7316 non-null   int64
 13  Contract                                 7316 non-null   int64
 14  PaperlessBilling                         7316 non-null   int64
 15  MonthlyCharges                           7316 non-null   float64
 16  Churn                                    7316 non-null   int64
 17  InternetService_Fiber optic              7316 non-null   int64
 18  InternetService_No                       7316 non-null   int64
 19  PaymentMethod_Bank transfer (automatic)  7316 non-null   int64
 20  PaymentMethod_Credit card                7316 non-null   int64
 21  PaymentMethod_Credit card (automatic)    7316 non-null   int64
 22  PaymentMethod_Electronic check           7316 non-null   int64
 23  PaymentMethod_Mailed check               7316 non-null   int64
dtypes: float64(1), int64(23)
memory usage: 1.3 MB

In [137]:
df_encoded.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaperlessBilling,MonthlyCharges,Churn,InternetService_Fiber optic,InternetService_No,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,1,5,0,1,0,1,0,...,1,27.43,1,0,1,0,1,0,0,0
1,0,0,0,0,42,1,0,1,1,0,...,0,38.28,1,0,0,0,0,0,1,0
2,1,0,0,0,61,1,0,0,1,0,...,0,106.44,1,0,1,0,0,0,0,0
3,1,1,0,1,22,1,0,0,0,1,...,0,92.49,0,0,1,0,0,0,1,0
4,1,1,1,1,21,0,0,0,0,0,...,0,19.63,1,0,0,0,0,0,0,0
5,0,0,1,0,70,1,0,0,1,1,...,1,43.21,0,0,1,0,0,0,1,0
6,1,1,1,0,1,0,0,0,0,0,...,0,39.80,1,0,0,0,1,0,0,0
7,1,1,0,1,5,0,1,0,0,0,...,0,45.47,0,0,1,0,1,0,0,0
8,1,1,0,1,12,0,1,0,0,0,...,1,43.13,0,0,0,0,0,0,0,0
9,0,1,0,0,46,1,0,0,0,0,...,1,24.53,1,1,0,0,0,0,1,0

In [138]:
corr = df_encoded.corr(numeric_only=True)
print(corr['Churn'].sort_values(ascending=False))

Churn                                      1.000000
InternetService_Fiber optic                0.291798
PaymentMethod_Electronic check             0.282861
MonthlyCharges                             0.182977
PaperlessBilling                           0.178079
SeniorCitizen                              0.152538
StreamingTV                                0.058463
PaymentMethod_Credit card                  0.057690
StreamingMovies                            0.056368
MultipleLines                              0.035257
gender                                    -0.008092
PhoneService                              -0.013231
DeviceProtection                          -0.057755
OnlineBackup                              -0.072456
PaymentMethod_Mailed check                -0.091127
PaymentMethod_Bank transfer (automatic)   -0.122769
PaymentMethod_Credit card (automatic)     -0.138192
Partner                                   -0.144061
Dependents                                -0.146987
TechSupport                               -0.156539
OnlineSecurity                            -0.164835
InternetService_No                        -0.211569
tenure                                    -0.336419
Contract                                  -0.373071
Name: Churn, dtype: float64

In [139]:
# droping columns with low correlation
df_encoded.drop(columns=['gender','PaymentMethod_Mailed check','OnlineBackup', 'DeviceProtection','PhoneService','MultipleLines','StreamingMovies','PaymentMethod_Credit card', 'StreamingTV'], inplace=True)

In [140]:
df_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 7316 entries, 0 to 7315
Data columns (total 15 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   SeniorCitizen                            7316 non-null   int64
 1   Partner                                  7316 non-null   int64
 2   Dependents                               7316 non-null   int64
 3   tenure                                   7316 non-null   int64
 4   OnlineSecurity                           7316 non-null   int64
 5   TechSupport                              7316 non-null   int64
 6   Contract                                 7316 non-null   int64
 7   PaperlessBilling                         7316 non-null   int64
 8   MonthlyCharges                           7316 non-null   float64
 9   Churn                                    7316 non-null   int64
 10  InternetService_Fiber optic              7316 non-null   int64
 11  InternetService_No                       7316 non-null   int64
 12  PaymentMethod_Bank transfer (automatic)  7316 non-null   int64
 13  PaymentMethod_Credit card (automatic)    7316 non-null   int64
 14  PaymentMethod_Electronic check           7316 non-null   int64
dtypes: float64(1), int64(14)
memory usage: 857.5 KB

In [141]:
df_encoded.head(10)

,SeniorCitizen,Partner,Dependents,tenure,OnlineSecurity,TechSupport,Contract,PaperlessBilling,MonthlyCharges,Churn,InternetService_Fiber optic,InternetService_No,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check
0,0,1,1,5,0,0,0,1,27.43,1,0,1,0,0,0
1,0,0,0,42,1,0,2,0,38.28,1,0,0,0,0,1
2,0,0,0,61,0,1,1,0,106.44,1,0,1,0,0,0
3,1,0,1,22,0,0,0,0,92.49,0,0,1,0,0,1
4,1,1,1,21,0,0,1,0,19.63,1,0,0,0,0,0
5,0,1,0,70,0,0,0,1,43.21,0,0,1,0,0,1
6,1,1,0,1,0,1,0,0,39.80,1,0,0,0,0,0
7,1,0,1,5,0,1,0,0,45.47,0,0,1,0,0,0
8,1,0,1,12,0,0,2,1,43.13,0,0,0,0,0,0
9,1,0,0,46,0,0,0,1,24.53,1,1,0,0,0,1

In [142]:
# skewness
numerical_cols = ['tenure', 'MonthlyCharges']
print(df_encoded[numerical_cols].skew())

tenure            0.226031
MonthlyCharges   -0.218278
dtype: float64

Both values are between -0.5 and 0.5 — that's the normal range, no transformation needed at all.

In [143]:
# creating directory if it doesn't exist
if not os.path.exists('DATA/processed'):
    os.makedirs('DATA/processed')

# save full clean dataset 
df_encoded.to_csv('../data/processed_data/featured_data.csv', index=False)